### ISSUE TITLE
EduNext API endpoints no longer need port!

### ISSUE THREAD

**Issue by Kunniii** [khengyun/autonext#25]
I just checked the extension this morning, the request to API server was not successful. This is because the API endpoint is no longer has a port, `8443` to be specific!

Please release a new version!! 🙌🙌🙌

**Comment by Kunniii** [comment]
Something stoopid is that, the `/api/auth/token` endpoints still using that `8443` port.

**Comment by khengyun** [comment]
Thank you for your assistance. I just rechecked and it appears that EduNext has removed the above port value. If a port value is not declared, APIs will use the default port values defined for each protocol type. For example, for HTTP and HTTPS, the default port values are 80 and 443, respectively. It's possible that they have decided to remove or change the port value on a weekly basis and unfortunately, I have not yet found a way to resolve this issue.

old:
![image](https://github.com/khengyun/autonext/assets/78076796/0a12b354-5872-45b6-a1fc-f0cbe88edd37)

new:
![image](https://github.com/khengyun/autonext/assets/78076796/6ea438ed-cb27-4489-b0df-ccbe39e817ad)

**Comment by Kunniii** [comment]
Looking forward to your fix, the extension is not working for now!!

```js
await newRelease();
```

**Comment by khengyun** [comment]
I have updated the new patch, you can check it here: [click](https://github.com/khengyun/autonext/commit/68fe670cd143073c941f0b113ff97c533e5ab122)

**Comment by khengyun** [comment]
> Looking forward to your fix, the extension is not working for now (at least, on my end)!!
> 
> ```js
> await newRelease();
> ```

you can check new release here: [https://github.com/khengyun/autonext/releases/tag/v3.5.2](v3.5.1)

**Comment by Kunniii** [comment]
Now the API uses port 8443, again, but `auth` endpoint doesn't! Nice play Edunext, i love you 3000

**Comment by khengyun** [comment]
> Now the API uses port 8443, again, but `auth` endpoint doesn't! Nice play Edunext, i love you 3000

maybe i will update the server to automatically update the port for the api 🤦‍♂️
